# Generated by Django 3.2 on 2021-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/wp3003513-iron-man-hd-wallpaper-for-mobile.jpg', upload_to='images/'),
        ),
    ]
