# Generated by Django 3.2 on 2021-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/wp3003513-iron-man-hd-wallpaper-for-mobile.jpg', null=True, upload_to='images'),
        ),
    ]
