# Generated by Django 3.2.4 on 2021-07-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210624_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sender',
            new_name='author',
        ),
    ]
